version: "3"

services:
  postgres:
    container_name: ignite
    image: postgres
    restart: "no"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ignite
